"""message

Revision ID: 11250e43cd25
Revises: 
Create Date: 2020-08-19 12:39:22.194028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11250e43cd25'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eegmachines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('devicename', sa.String(), nullable=True),
    sa.Column('devicemode', sa.String(), nullable=True),
    sa.Column('recordchannelsettinggroup', sa.String(), nullable=True),
    sa.Column('recordmontagename', sa.String(), nullable=True),
    sa.Column('recordprotocolname', sa.String(), nullable=True),
    sa.Column('recordeegcapname', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eegscans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('examid', sa.String(), nullable=True),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('eegmachine_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('examitem', sa.String(), nullable=True),
    sa.Column('impedancepos', sa.String(), nullable=True),
    sa.Column('impedancedata', sa.String(), nullable=True),
    sa.Column('impedanceonline', sa.Boolean(), nullable=True),
    sa.Column('begintimestamp', sa.String(), nullable=True),
    sa.Column('digitalmin', sa.Integer(), nullable=True),
    sa.Column('digitalmax', sa.Integer(), nullable=True),
    sa.Column('physicalmin', sa.Float(), nullable=True),
    sa.Column('physicalmax', sa.Float(), nullable=True),
    sa.Column('samplerate', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['eegmachine_id'], ['eegmachines.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('association_group_eegscan',
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('scan_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['scan_id'], ['eegscans.id'], )
    )
    op.drop_table('strokescores')
    op.rename_table('association_group_scan','association_group_mriscan')
    op.drop_table('motionscores')
    #op.drop_constraint(None, 'mriscans', type_='foreignkey')
    #op.drop_column('mriscans', 'group_id')
    op.add_column('people', sa.Column('datasource', sa.String(), nullable=True))
    op.add_column('people', sa.Column('eegid', sa.String(), nullable=True))
    op.add_column('people', sa.Column('mriid', sa.String(), nullable=True))
    op.alter_column('people','name', new_column_name= 'name_pinyin')
    op.add_column('people', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('people', 'name_pinyin')
    op.drop_column('people', 'mriid')
    op.drop_column('people', 'eegid')
    op.drop_column('people', 'datasource')
    op.add_column('mriscans', sa.Column('group_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'mriscans', 'groups', ['group_id'], ['id'])
    op.create_table('motionscores',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('person_id', sa.INTEGER(), nullable=True),
    sa.Column('mriscan_id', sa.INTEGER(), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.Column('scTSI', sa.FLOAT(), nullable=True),
    sa.Column('scMotor', sa.FLOAT(), nullable=True),
    sa.Column('scSensory', sa.FLOAT(), nullable=True),
    sa.Column('scVAS', sa.FLOAT(), nullable=True),
    sa.Column('scMAS', sa.FLOAT(), nullable=True),
    sa.Column('scWISCI2', sa.FLOAT(), nullable=True),
    sa.Column('scSCIM', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['mriscan_id'], ['mriscans.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('association_group_scan',
    sa.Column('group_id', sa.INTEGER(), nullable=True),
    sa.Column('scan_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['scan_id'], ['mriscans.id'], )
    )
    op.create_table('strokescores',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('person_id', sa.INTEGER(), nullable=True),
    sa.Column('mriscan_id', sa.INTEGER(), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.Column('scFMA', sa.FLOAT(), nullable=True),
    sa.Column('scARAT', sa.FLOAT(), nullable=True),
    sa.Column('scWOLF', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['mriscan_id'], ['mriscans.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('association_group_mriscan')
    op.drop_table('association_group_eegscan')
    op.drop_table('eegscans')
    op.drop_table('eegmachines')
    # ### end Alembic commands ###
