"""empty message

Revision ID: 38611286ecd3
Revises: 11250e43cd25
Create Date: 2020-09-22 12:57:07.822560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38611286ecd3'
down_revision = '11250e43cd25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.add_column('people', sa.Column('name_chinese', sa.String(), nullable=True))
    op.drop_column('people', 'name_pinyin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('name_pinyin', sa.VARCHAR(), nullable=True))
    op.drop_column('people', 'name_chinese')
    # ### end Alembic commands ###
